---
- name: Install MySQL Server
  ansible.builtin.apt:
    name: mysql-server
    state: present
  become: true

- name: Install Python MySQL dependencies
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  become: true

- name: Ensure MySQL service is running
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Wait for MySQL to become available
  ansible.builtin.wait_for:
    port: 3306
    delay: 10
    timeout: 30
  become: true

- name: Create MySQL database
  community.mysql.mysql_db:
    name: dbsafouane
    state: present
    login_user: dbuser
    login_password: "{{ mysql_password }}"
  become: true

- name: Create MySQL user 'dbuser'
  community.mysql.mysql_user:
    name: dbuser
    password: "{{ mysql_password }}"
    priv: "dbsafouane.*:ALL"
    state: present
    host: "%"
    login_user: dbuser
    login_password: "{{ mysql_password }}"
  become: true
